/**
 * Catálogo de plantillas de Correos Transaccionales.
 *
 * Esquema de cada entrada (Módulo 2 — Biblioteca de Plantillas):
 *   id            -> identificador único, kebab-case, igual al nombre de archivo sin extensión
 *   nombre        -> nombre visible de la plantilla
 *   plataforma    -> "VTEX" | "PIM" | otra plataforma futura
 *   canales       -> canales comerciales donde aplica: "punto-de-venta" | "b2c" | "b2b" | "ext"
 *   tiendas       -> marcas/negocios donde aplica: "sporting" | "woker" (B2C) | "venta-deportiva" (B2B) | "seller-adidas" (EXT). PV no tiene tienda.
 *   logistica     -> medios de envío donde aplica: "andreani" | "ocasa" | "propia" | "retiro" |
 *                    "producteca-oca" | "producteca-correo-argentino" | "producteca-trf" | "producteca-urbano"
 *   evento        -> evento funcional normalizado ({ id, label })
 *   stageId       -> etapa comun del flujo general (derivada de evento)
 *   categoria     -> etapa del flujo (ver modules/flujo): "Logística de Entrega",
 *                    "Logística inversa - Cambio", "Logística inversa - Devolución",
 *                    "Logística inversa - Garantía"
 *   estado        -> "activo" | "en revisión" | "deprecado"
 *   actualizado   -> fecha de última actualización (YYYY-MM-DD)
 *   responsable   -> dueño/a funcional de la plantilla
 *   descripcion   -> qué dispara el envío y a quién
 *   archivoHtml   -> ruta relativa al HTML real dentro de templates/
 *   ejemplo       -> ruta relativa al JSON de datos de ejemplo dentro de examples/ (puede ser null si aún no hay)
 *   variables     -> lista de variables/datos clave que usa la plantilla (para consulta rápida,
 *                    no es la lista exhaustiva de helpers Handlebars del HTML)
 *
 * EXAMPLE_SCENARIOS centraliza los JSON disponibles para previsualización.
 *   id                  -> identificador estable del escenario
 *   path                -> ruta relativa al JSON dentro de examples/
 *   label               -> nombre visible del escenario
 *   tipo                -> familia funcional del JSON
 *   descripcion         -> variante que representa
 *   canales             -> canales comerciales donde aplica el escenario
 *   tiendas             -> tiendas/marcas donde aplica el escenario
 *   logistica           -> medios de envío que representa el escenario (opcional)
 *   eventoId            -> id del evento funcional asociado
 *   compatibleTemplates -> ids de plantillas que pueden renderizarse con ese JSON
 */

const TEMPLATES = [
  {
    id: 'pedido-confirmado',
    nombre: 'Pedido realizado Sporting',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'activo',
    actualizado: '2026-06-06',
    responsable: 'Por definir',
    descripcion: 'Confirma al cliente que su pedido fue registrado correctamente, con resumen de productos, totales, dirección y forma de pago.',
    archivoHtml: 'templates/vtex/sporting/pedido-confirmado/pedido-confirmado.v2.html',
    ejemplo: 'examples/vtex/sporting/pedido-estandar.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orders.0.orderId',
      'orders.0.creationDate',
      'orders.0.clientProfileData.firstName',
      'orders.0.value (formatCurrency)',
      'orders.0.items[] (skuName, quantity, listPrice, sellingPrice, imageUrl)',
      'orders.0.totals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'orders.0.shippingData.selectedAddresses[0] (street, number, complement, city, state, postalCode)',
      'orders.0.shippingData.logisticsInfo[0].deliveryIds[0].courierName',
      'orders.0.paymentData.transactions[].payments[] (paymentSystemName, installments, lastDigits, connectorResponses.authId)',
      'orders.0.ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
      'orders.0.items[] (imageUrl, detailUrl — usados en links de producto)',
    ],
  },
  {
    id: 'woker-pedido-confirmado',
    nombre: 'Pedido realizado Woker',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma al cliente Woker que su pedido fue registrado correctamente, con resumen de productos, totales, dirección y forma de pago.',
    archivoHtml: 'templates/vtex/woker/pedido-confirmado/pedido-confirmado.v2.html',
    ejemplo: 'examples/vtex/woker/pedido-estandar.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orders.0.orderId',
      'orders.0.creationDate',
      'orders.0.clientProfileData.firstName',
      'orders.0.value (formatCurrency)',
      'orders.0.items[] (skuName, quantity, listPrice, sellingPrice, imageUrl)',
      'orders.0.totals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'orders.0.shippingData.selectedAddresses[0] (street, number, complement, city, state, postalCode)',
      'orders.0.shippingData.logisticsInfo[0].deliveryIds[0].courierName',
      'orders.0.paymentData.transactions[].payments[] (paymentSystemName, installments, lastDigits, connectorResponses.authId)',
      'orders.0.ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
      'orders.0.items[] (imageUrl, detailUrl — usados en links de producto)',
    ],
  },
  {
    id: 'pedido-cancelado',
    nombre: 'Pedido cancelado Sporting',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'activo',
    actualizado: '2026-06-08',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que su pedido fue cancelado e informa el proceso de reintegro según el medio de pago.',
    archivoHtml: 'templates/vtex/sporting/pedido-cancelado/pedido-cancelado.v2.html',
    ejemplo: 'examples/vtex/sporting/pedido-cancelado.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orderId',
      'creationDate',
      'clientProfileData.firstName',
      'value (formatCurrency)',
      'cancellationData.cancellationDate',
      'cancellationData.reason',
      'items[] (name, skuName, brandName, quantity, listPrice, sellingPrice, imageUrl, priceDefinition.total)',
      'totals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'shippingData.selectedAddresses[0] (receiverName, street, number, city, state, postalCode)',
      'shippingData.logisticsInfo[0].selectedDeliveryChannel',
      'paymentData.transactions[].payments[] (paymentSystemName, value, installments, lastDigits, group, connectorResponses.authId)',
      'ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
    ],
  },
  {
    id: 'woker-pedido-cancelado',
    nombre: 'Pedido cancelado Woker',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente Woker que su pedido fue cancelado e informa el proceso de reintegro según el medio de pago.',
    archivoHtml: 'templates/vtex/woker/pedido-cancelado/pedido-cancelado.v2.html',
    ejemplo: 'examples/vtex/woker/pedido-cancelado.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orderId',
      'creationDate',
      'clientProfileData.firstName',
      'value (formatCurrency)',
      'cancellationData.cancellationDate',
      'cancellationData.reason',
      'items[] (name, skuName, brandName, quantity, listPrice, sellingPrice, imageUrl, priceDefinition.total)',
      'totals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'shippingData.selectedAddresses[0] (receiverName, street, number, city, state, postalCode)',
      'shippingData.logisticsInfo[0].selectedDeliveryChannel',
      'paymentData.transactions[].payments[] (paymentSystemName, value, installments, lastDigits, group, connectorResponses.authId)',
      'ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
    ],
  },
  {
    id: 'pago-aprobado',
    nombre: 'Pago aprobado Sporting',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'activo',
    actualizado: '2026-06-06',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que el pago de su pedido fue aprobado, con resumen de productos, totales, envío/retiro y forma de pago.',
    archivoHtml: 'templates/vtex/sporting/pago-aprobado/pago-aprobado.v2.html',
    ejemplo: 'examples/vtex/sporting/pedido-estandar.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orderId',
      'creationDate',
      'clientProfileData.firstName',
      'items[] (skuName, quantity, listPrice, sellingPrice, imageUrl, detailUrl)',
      'totals[] / alternativeTotals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'shippingData.selectedAddresses[0] (street, number, complement, city, state, postalCode)',
      'shippingData.logisticsInfo[] (selectedDeliveryChannel, shippingEstimateDate, deliveryIds[0].courierName)',
      'paymentData.transactions[].payments[] (paymentSystemName, installments, lastDigits, connectorResponses.authId)',
      'ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
    ],
  },
  {
    id: 'woker-pago-aprobado',
    nombre: 'Pago aprobado Woker',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente Woker que el pago de su pedido fue aprobado, con resumen de productos, totales, envío/retiro y forma de pago.',
    archivoHtml: 'templates/vtex/woker/pago-aprobado/pago-aprobado.v2.html',
    ejemplo: 'examples/vtex/woker/pago-aprobado.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orderId',
      'creationDate',
      'clientProfileData.firstName',
      'items[] (skuName, quantity, listPrice, sellingPrice, imageUrl, detailUrl)',
      'totals[] / alternativeTotals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'shippingData.selectedAddresses[0] (street, number, complement, city, state, postalCode)',
      'shippingData.logisticsInfo[] (selectedDeliveryChannel, shippingEstimateDate, deliveryIds[0].courierName)',
      'paymentData.transactions[].payments[] (paymentSystemName, installments, lastDigits, connectorResponses.authId)',
      'ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
    ],
  },
  {
    id: 'access-key',
    nombre: 'Código de acceso Sporting',
    plataforma: 'VTEX',
    categoria: 'Cuenta',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Envía un código de verificación al cliente cuando solicita ingresar o recuperar acceso a su cuenta.',
    archivoHtml: 'templates/vtex/sporting/access-key/access-key.v2.html',
    ejemplo: 'examples/vtex/sporting/access-key.sample.json',
    variables: [
      'to[0].name',
      'aditionalData.accessKey',
      'aditionalData.userAgent',
      '_accountInfo.TradingName',
      '_accountInfo.AccountName',
      '_accountInfo.HostName',
    ],
  },
  {
    id: 'b2b-access-key',
    nombre: 'Código de acceso B2B',
    plataforma: 'VTEX',
    categoria: 'Cuenta',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Envía un código de verificación al comprador B2B cuando solicita ingresar a su cuenta.',
    archivoHtml: 'templates/vtex/b2b/access-key/access-key.v2.html',
    ejemplo: 'examples/vtex/sporting/access-key.sample.json',
    variables: [
      'to[0].name',
      'aditionalData.accessKey',
      'aditionalData.userAgent',
      '_accountInfo.TradingName',
      '_accountInfo.AccountName',
      '_accountInfo.HostName',
    ],
  },
  {
    id: 'woker-access-key',
    nombre: 'Código de acceso Woker',
    plataforma: 'VTEX',
    categoria: 'Cuenta',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Envía un código de verificación al cliente Woker cuando solicita ingresar o recuperar acceso a su cuenta.',
    archivoHtml: 'templates/vtex/woker/access-key/access-key.v2.html',
    ejemplo: 'examples/vtex/woker/access-key.sample.json',
    variables: [
      'to[0].name',
      'aditionalData.accessKey',
      'aditionalData.userAgent',
      '_accountInfo.TradingName',
      '_accountInfo.AccountName',
      '_accountInfo.HostName',
    ],
  },
  {
    id: 'back-in-stock',
    nombre: 'Volvió a stock Sporting',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente suscrito que un SKU sin stock volvió a estar disponible para comprar.',
    archivoHtml: 'templates/vtex/sporting/back-in-stock/back-in-stock.v2.html',
    ejemplo: 'examples/vtex/sporting/back-in-stock.sample.json',
    variables: [
      'NotifyRequest.name',
      'NotifyRequest.locale',
      'NotifyRequest.seller.addToCartLink',
      'SkuContext.NameComplete',
      'SkuContext.ProductName',
      'SkuContext.SkuName',
      'SkuContext.ImageUrl',
      'SkuContext.DetailUrl',
      '_accountInfo.TradingName',
    ],
  },
  {
    id: 'woker-back-in-stock',
    nombre: 'Volvió a stock Woker',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente Woker suscrito que un SKU sin stock volvió a estar disponible para comprar.',
    archivoHtml: 'templates/vtex/woker/back-in-stock/back-in-stock.v2.html',
    ejemplo: 'examples/vtex/woker/back-in-stock.sample.json',
    variables: [
      'NotifyRequest.name',
      'NotifyRequest.locale',
      'NotifyRequest.seller.addToCartLink',
      'SkuContext.NameComplete',
      'SkuContext.ProductName',
      'SkuContext.SkuName',
      'SkuContext.Images[0].ImageUrl / SkuContext.ImageUrl',
      'SkuContext.DetailUrl',
      '_accountInfo.TradingName',
    ],
  },
  {
    id: 'order-invoiced',
    nombre: 'Pedido facturado Sporting',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que su pedido fue facturado, con acceso a las facturas y datos de seguimiento del despacho.',
    archivoHtml: 'templates/vtex/sporting/order-invoiced/order-invoiced.v2.html',
    ejemplo: 'examples/vtex/sporting/order-invoiced.sample.json',
    variables: [
      'orderId',
      'clientProfileData.firstName',
      'hostName / _accountInfo.HostName',
      '_accountInfo.TradingName',
      'packages[] (invoiceNumber, invoiceValue, invoiceUrl, issuanceDate, courier, trackingNumber, trackingUrl)',
      'package.* (fallback cuando no hay packages[])',
      'shippingData.address (street, number, city, state, country)',
      'paymentData.transactions[].payments[] (paymentSystemName, installments)',
    ],
  },
  {
    id: 'b2b-orden-generada',
    nombre: 'Orden generada B2B',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma a un comprador B2B que la orden fue generada y queda pendiente de validación comercial antes de avanzar al resto del flujo.',
    archivoHtml: 'templates/vtex/b2b/orden-generada/orden-generada.v2.html',
    ejemplo: 'examples/vtex/b2b/orden-generada.sample.json',
    variables: [
      '_accountInfo.TradingName',
      'ordersUrl',
      'orderId',
      'creationDate',
      'clientProfileData.firstName / lastName / email / document',
      'value (formatCurrency)',
      'items[] (name, skuName, quantity, sellingPrice, priceDefinition.total, imageUrl, detailUrl)',
      'subjectItemAttachment.totalItems',
      'totals[] (Items, Discounts, Shipping, Tax)',
      'shippingData.selectedAddresses[0] / shippingData.address',
      'shippingData.logisticsInfo[0] (selectedDeliveryChannel, shippingEstimateDate)',
      'paymentData.transactions[].payments[] (paymentSystemName, group, value, installments)',
    ],
  },
  {
    id: 'pim-envio-despachado',
    nombre: 'Pedido despachado (nuevo envío)',
    plataforma: 'PIM',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-10',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que su pedido fue despachado e informa operador logistico, numero de seguimiento y proximo paso.',
    archivoHtml: 'templates/pim/shared/envio-despachado/envio-despachado.v2.html',
    ejemplo: 'examples/pim/shared/envio-despachado.sample.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.DatosEnvio.Destinatario.Nombres',
      'Pedido.Logistica',
      'Pedido.DatosEnvio.Etiqueta.NroSeguimiento',
    ],
  },
  {
    id: 'pim-pedido-confirmado-pv',
    nombre: 'Confirmación de compra (Venta Multidepósito)',
    plataforma: 'PIM',
    categoria: 'Confirmación de Compra',
    estado: 'en revisión',
    actualizado: '2026-06-10',
    responsable: 'Por definir',
    descripcion: 'Confirmación inicial de compra para ventas multidepósito (compra en sucursal con envío posterior). Centraliza compra registrada, pago aprobado, pedido generado y factura adjunta; explica próximas etapas e informa políticas de cambios y reembolsos. Reemplaza a los correos VTEX de pedido realizado, pago aprobado y pedido facturado.',
    archivoHtml: 'templates/pim/shared/pedido-confirmado-pv/pedido-confirmado-pv.v2.html',
    ejemplo: 'examples/pim/shared/pedido-confirmado-pv-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.FechaPedido',
      'Pedido.DatosEnvio.Destinatario.Nombres',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Importe',
      'Pedido.LineasPedido[].Cantidad',
      'Pedido.LineasPedido[].Subtotal',
      'Pedido.TotalLineas',
    ],
  },
  {
    id: 'pim-quiebre-stock-pv',
    nombre: 'Sin stock PV',
    plataforma: 'PIM',
    categoria: 'Cancelacion / Reembolso',
    estado: 'en revision',
    actualizado: '2026-06-11',
    responsable: 'Por definir',
    descripcion: 'Informa un quiebre de stock en pedidos de Punto de Venta y ofrece alternativas operativas: cambio en sucursal, reembolso presencial en la sucursal de compra o giftcard-enviada para tiendas online.',
    archivoHtml: 'templates/pim/shared/quiebre-stock-pv/quiebre-stock-pv.v2.html',
    ejemplo: 'examples/pim/shared/quiebre-stock-pv-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.FechaPedido',
      'Pedido.DatosEnvio.Destinatario.Nombres',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Cantidad',
      'Pedido.LineasPedido[].Estado',
      'Pedido.TotalLineas',
      'Deposito.DatosDeposito.DatosPickup.NombrePublico',
      'Deposito.DatosDeposito.DatosPickup.Direccion',
      'Deposito.DatosDeposito.DatosPickup.Localidad',
      'Deposito.DatosDeposito.DatosPickup.Horario',
    ],
  },
  {
    id: 'pim-retiro-disponible',
    nombre: 'Pedido listo para retirar (pickup)',
    plataforma: 'PIM',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-10',
    responsable: 'Por definir',
    descripcion: 'Informa que el pedido está listo para retirar en la sucursal seleccionada, con resumen de compra, productos, lugar de retiro (dirección y horario) y requisitos. Reemplaza a la plantilla vieja nuevo-pickup.',
    archivoHtml: 'templates/pim/shared/retiro-disponible/retiro-disponible.v2.html',
    ejemplo: 'examples/pim/shared/retiro-disponible-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.FechaPedido',
      'Pedido.DatosEnvio.Destinatario.Nombres',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Importe',
      'Pedido.LineasPedido[].Cantidad',
      'Pedido.LineasPedido[].Subtotal',
      'Pedido.TotalLineas',
      'Deposito.DatosDeposito.DatosPickup.NombrePublico',
      'Deposito.DatosDeposito.DatosPickup.Direccion',
      'Deposito.DatosDeposito.DatosPickup.Localidad',
      'Deposito.DatosDeposito.DatosPickup.Horario',
    ],
  },
  {
    id: 'pim-envio-b2b',
    nombre: 'Despacho B2B',
    plataforma: 'PIM',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma una orden B2B en preparacion, con datos de envio, productos y totales. Header dinamico asumido (la version vieja hardcodeaba el logo).',
    archivoHtml: 'templates/pim/shared/envio-b2b/envio-b2b.v2.html',
    ejemplo: 'examples/pim/shared/envio-b2b-venta-deportiva.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.FechaPedido',
      'Pedido.DatosEnvio.Destinatario.Nombres',
      'Pedido.DatosEnvio.Destino.Postal.Calle',
      'Pedido.DatosEnvio.Destino.Postal.Numero',
      'Pedido.DatosEnvio.Destino.Postal.Localidad',
      'Pedido.DatosEnvio.Destino.Postal.Pais',
      'Pedido.DatosEnvio.Destino.Postal.CodigoPostal',
      'Pedido.DatosEnvio.Destino.Postal.Referencia',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Importe',
      'Pedido.LineasPedido[].Cantidad',
      'Pedido.LineasPedido[].Subtotal',
      'Pedido.TotalLineas',
    ],
  },
  {
    id: 'pim-giftcard-enviada',
    nombre: 'Giftcard (código de cambio)',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Cambio',
    estado: 'en revisión',
    actualizado: '2026-06-10',
    responsable: 'Por definir',
    descripcion: 'Informa la emision de una giftcard-enviada/codigo para resolver un cambio, devolucion o falta de stock, con el codigo destacado, saldo inicial, observaciones y condiciones de uso.',
    archivoHtml: 'templates/pim/shared/giftcard-enviada/giftcard-enviada.v2.html',
    ejemplo: 'examples/pim/shared/giftcard-enviada-sporting.json',
    variables: [
      'Proveedor.GetEmailHeaderURL',
      'Proveedor.GetEmailHeaderImage',
      'Giftcard.Codigo',
      'Giftcard.SaldoInicial',
      'Giftcard.Descripcion',
    ],
  },
  {
    id: 'pim-recepcion-cambio',
    nombre: 'Recepcion de cambio',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Cambio',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma la recepcion de productos vinculados a un cambio e informa estados aceptados o rechazados (con motivo de rechazo).',
    archivoHtml: 'templates/pim/shared/recepcion-cambio/recepcion-cambio.v2.html',
    ejemplo: 'examples/pim/shared/recepcion-cambio-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Cantidad',
      'Pedido.LineasPedido[].Estado',
      'Pedido.LineasPedido[].Historial[0].Observaciones',
    ],
  },
  {
    id: 'pim-recepcion-devolucion',
    nombre: 'Recepcion de devolucion',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Devolución',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma la recepcion de productos devueltos (estados aceptados o rechazados con motivo) e informa el plazo de reembolso.',
    archivoHtml: 'templates/pim/shared/recepcion-devolucion/recepcion-devolucion.v2.html',
    ejemplo: 'examples/pim/shared/recepcion-devolucion-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Cantidad',
      'Pedido.LineasPedido[].Estado',
      'Pedido.LineasPedido[].Historial[0].Observaciones',
    ],
  },
  {
    id: 'pim-recepcion-garantia',
    nombre: 'Recepcion de garantia',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Garantía',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma la recepcion de un producto en garantia (estados aceptados o rechazados con motivo) e informa proximos pasos y plazos de reembolso.',
    archivoHtml: 'templates/pim/shared/recepcion-garantia/recepcion-garantia.v2.html',
    ejemplo: 'examples/pim/shared/recepcion-garantia-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Cantidad',
      'Pedido.LineasPedido[].Estado',
      'Pedido.LineasPedido[].Historial[0].Observaciones',
    ],
  },
  {
    id: 'pim-quiebre-stock',
    nombre: 'Quiebre de stock',
    plataforma: 'PIM',
    categoria: 'Cancelacion / Reembolso',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Informa el quiebre de stock por error de inventario: lista los artículos dados de baja y los plazos de reintegro según el medio de pago.',
    archivoHtml: 'templates/pim/shared/quiebre-stock/quiebre-stock.v2.html',
    ejemplo: 'examples/pim/shared/quiebre-stock-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Cantidad',
      'Pedido.LineasPedido[].Estado',
    ],
  },
  {
    id: 'pim-factura-disponible',
    nombre: 'Factura disponible',
    plataforma: 'PIM',
    categoria: 'Facturación',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica que la factura electronica esta disponible y adjunta al correo. Muestra el N° de pedido si el flujo lo expone.',
    archivoHtml: 'templates/pim/shared/factura-disponible/factura-disponible.v2.html',
    ejemplo: 'examples/pim/shared/factura-disponible-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal (opcional / condicional)',
    ],
  },
  {
    id: 'pim-etiqueta-devolucion',
    nombre: 'Etiqueta de devolucion',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Devolución',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Informa que la devolucion esta en gestion: la etiqueta viaja adjunta al correo y el operador logistico retira los productos a domicilio. Lista los productos a devolver.',
    archivoHtml: 'templates/pim/shared/etiqueta-devolucion/etiqueta-devolucion.v2.html',
    ejemplo: 'examples/pim/shared/etiqueta-devolucion-sporting.json',
    variables: [
      'Tienda.Nombre',
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[].Producto',
      'Pedido.LineasPedido[].SKU',
      'Pedido.LineasPedido[].Cantidad',
    ],
  },
];

const EXAMPLE_SCENARIOS = [
  {
    id: 'pedido-estandar-domicilio',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/vtex/sporting/pedido-estandar.sample.json',
    label: 'Pedido estándar - envío a domicilio',
    tipo: 'Pedido',
    descripcion: 'Pedido confirmado con varios productos, totales, dirección de entrega y pago registrado.',
    compatibleTemplates: ['pedido-confirmado', 'pago-aprobado'],
  },
  {
    id: 'pedido-estandar-woker',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/vtex/woker/pedido-estandar.sample.json',
    label: 'Woker - pedido estándar',
    tipo: 'Pedido',
    descripcion: 'Pedido Woker confirmado con varios productos, totales, dirección de entrega y pago registrado.',
    compatibleTemplates: ['woker-pedido-confirmado'],
  },
  {
    id: 'pedido-realizado-exito',
    facetas: ['un-paquete'],
    path: 'examples/vtex/sporting/pedido-realizado.sample.json',
    label: 'Pedido realizado - 1 producto',
    tipo: 'Pedido',
    descripcion: 'Pedido confirmado simple para validar la rama base de compra realizada.',
    compatibleTemplates: ['pedido-confirmado', 'pago-aprobado'],
  },
  {
    id: 'pago-aprobado-base',
    facetas: ['un-paquete'],
    path: 'examples/vtex/sporting/pago-aprobado.sample.json',
    label: 'Pago aprobado - pedido base',
    tipo: 'Pedido',
    descripcion: 'Pedido con pago aprobado, datos de medio de pago y logística de entrega.',
    compatibleTemplates: ['pago-aprobado', 'pedido-confirmado'],
  },
  {
    id: 'pago-aprobado-woker',
    facetas: ['un-paquete'],
    path: 'examples/vtex/woker/pago-aprobado.sample.json',
    label: 'Woker - pago aprobado',
    tipo: 'Pedido',
    descripcion: 'Pedido Woker con pago aprobado, datos de medio de pago y logística de entrega.',
    compatibleTemplates: ['woker-pago-aprobado'],
  },
  {
    id: 'pedido-cancelado-un-producto',
    facetas: ['un-paquete'],
    path: 'examples/vtex/sporting/pedido-cancelado.sample.json',
    label: 'Cancelación - 1 producto',
    tipo: 'Cancelación',
    descripcion: 'Pedido cancelado con reintegro y un producto en el resumen.',
    compatibleTemplates: ['pedido-cancelado'],
  },
  {
    id: 'pedido-cancelado-woker',
    path: 'examples/vtex/woker/pedido-cancelado.sample.json',
    label: 'Woker - pedido cancelado',
    tipo: 'Cancelación',
    descripcion: 'Pedido Woker cancelado con reintegro y productos en el resumen.',
    compatibleTemplates: ['woker-pedido-cancelado'],
  },
  {
    id: 'pedido-cancelado-envio-gratis',
    facetas: ['un-paquete', 'envio-gratis'],
    path: 'examples/vtex/sporting/pedido-cancelado-2.sample.json',
    label: 'Cancelación - 2 productos, envío gratis',
    tipo: 'Cancelación',
    descripcion: 'Pedido cancelado con más de un producto y condición de envío bonificado.',
    compatibleTemplates: ['pedido-cancelado'],
  },
  {
    id: 'access-key-login',
    path: 'examples/vtex/sporting/access-key.sample.json',
    store: 'shared',
    label: 'Acceso a cuenta - código de ingreso',
    tipo: 'Cuenta',
    descripcion: 'Evento de login o recuperación con código de verificación.',
    compatibleTemplates: ['access-key', 'b2b-access-key'],
  },
  {
    id: 'access-key-woker',
    path: 'examples/vtex/woker/access-key.sample.json',
    label: 'Woker - acceso a cuenta',
    tipo: 'Cuenta',
    descripcion: 'Evento de login o recuperación de Woker con código de verificación.',
    compatibleTemplates: ['woker-access-key'],
  },
  {
    id: 'back-in-stock-disponible',
    path: 'examples/vtex/sporting/back-in-stock.sample.json',
    label: 'Stock - SKU disponible',
    tipo: 'Stock',
    descripcion: 'Aviso a cliente suscrito cuando un SKU vuelve a estar disponible.',
    compatibleTemplates: ['back-in-stock'],
  },
  {
    id: 'back-in-stock-woker',
    path: 'examples/vtex/woker/back-in-stock.sample.json',
    label: 'Woker - SKU disponible',
    tipo: 'Stock',
    descripcion: 'Aviso a cliente Woker suscrito cuando un SKU vuelve a estar disponible.',
    compatibleTemplates: ['woker-back-in-stock'],
  },
  {
    id: 'order-invoiced-seguimiento',
    facetas: ['un-paquete'],
    path: 'examples/vtex/sporting/order-invoiced.sample.json',
    label: 'Facturación - con seguimiento',
    tipo: 'Facturación',
    descripcion: 'Pedido facturado con paquete, factura y datos de tracking.',
    compatibleTemplates: ['order-invoiced'],
  },
  {
    id: 'b2b-orden-generada-base',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/vtex/b2b/orden-generada.sample.json',
    label: 'B2B - orden generada',
    tipo: 'B2B',
    descripcion: 'Orden B2B recibida con pago a validar, varios productos y entrega a domicilio.',
    compatibleTemplates: ['b2b-orden-generada'],
  },
  {
    id: 'pim-envio-despachado-andreani',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/pim/shared/envio-despachado.sample.json',
    store: 'shared',
    label: 'Andreani',
    tipo: 'PIM — pedido despachado',
    descripcion: 'Despacho por Andreani con número de seguimiento activo. Link directo al tracking.',
    compatibleTemplates: ['pim-envio-despachado'],
  },
  {
    id: 'pim-envio-despachado-producteca-urbano',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/pim/shared/envio-despachado-producteca-urbano.json',
    store: 'shared',
    label: 'Producteca → Urbano (UR…)',
    tipo: 'PIM — pedido despachado',
    descripcion: 'Despacho por Producteca con tracking Urbano (prefijo UR). Muestra "Urbano" como carrier real.',
    compatibleTemplates: ['pim-envio-despachado'],
  },
  {
    id: 'pim-envio-despachado-producteca-correo-argentino',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/pim/shared/envio-despachado-producteca-correo-argentino.json',
    store: 'shared',
    label: 'Producteca → Correo Argentino (CA…)',
    tipo: 'PIM — pedido despachado',
    descripcion: 'Despacho por Producteca con tracking Correo Argentino (prefijo CA). Muestra "Correo Argentino" como carrier real.',
    compatibleTemplates: ['pim-envio-despachado'],
  },
  {
    id: 'pim-envio-despachado-producteca-oca',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/pim/shared/envio-despachado-producteca-oca.json',
    store: 'shared',
    label: 'Producteca → OCA (numérico largo)',
    tipo: 'PIM — pedido despachado',
    descripcion: 'Despacho por Producteca con tracking OCA (número largo >12 dígitos). Muestra "OCA" como carrier real.',
    compatibleTemplates: ['pim-envio-despachado'],
  },
  {
    id: 'pim-envio-despachado-producteca-trf',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/pim/shared/envio-despachado-producteca-trf.json',
    store: 'shared',
    label: 'Producteca → TRF (numérico corto)',
    tipo: 'PIM — pedido despachado',
    descripcion: 'Despacho por Producteca con tracking TRF (número corto ≤12 dígitos). Muestra "TRF" como carrier real.',
    compatibleTemplates: ['pim-envio-despachado'],
  },
  {
    id: 'pim-envio-despachado-producteca-sin-tracking',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/pim/shared/envio-despachado-producteca-sin-tracking.json',
    store: 'shared',
    label: 'Producteca — sin tracking aún',
    tipo: 'PIM — pedido despachado',
    descripcion: 'Despacho por Producteca sin número de seguimiento disponible. Muestra el mensaje de espera en lugar del botón.',
    compatibleTemplates: ['pim-envio-despachado'],
  },
  {
    id: 'pim-envio-despachado-ocasa',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/pim/shared/envio-despachado-ocasa.json',
    store: 'shared',
    label: 'OCASA',
    tipo: 'PIM — pedido despachado',
    descripcion: 'Despacho por OCASA con número de tracking embebido en el link de seguimiento.',
    compatibleTemplates: ['pim-envio-despachado'],
  },
  {
    id: 'pim-envio-despachado-propia',
    facetas: ['un-paquete', 'domicilio'],
    path: 'examples/pim/shared/envio-despachado-propia.json',
    store: 'shared',
    label: 'Logística Propia',
    tipo: 'PIM — pedido despachado',
    descripcion: 'Despacho con logística propia. Sin botón de tracking; muestra mensaje de coordinación de entrega.',
    compatibleTemplates: ['pim-envio-despachado'],
  },
  {
    id: 'pim-pedido-confirmado-pv-sporting',
    facetas: ['multideposito'],
    path: 'examples/pim/shared/pedido-confirmado-pv-sporting.json',
    store: 'shared',
    label: 'Sporting (2 productos)',
    tipo: 'PIM — confirmación multidepósito',
    descripcion: 'Confirmación de compra multidepósito de Sporting con dos productos y portal de gestión propio.',
    compatibleTemplates: ['pim-pedido-confirmado-pv'],
  },
  {
    id: 'pim-pedido-confirmado-pv-woker',
    facetas: ['un-paquete'],
    path: 'examples/pim/shared/pedido-confirmado-pv-woker.json',
    store: 'shared',
    label: 'Woker (1 producto)',
    tipo: 'PIM — confirmación multidepósito',
    descripcion: 'Confirmación de compra multidepósito de Woker con un producto; valida la marca dinámica y el portal de gestión de Woker.',
    compatibleTemplates: ['pim-pedido-confirmado-pv'],
  },
  {
    id: 'pim-quiebre-stock-pv-sporting',
    path: 'examples/pim/shared/quiebre-stock-pv-sporting.json',
    store: 'shared',
    label: 'Sporting (2 productos sin stock)',
    tipo: 'PIM - sin stock PV',
    descripcion: 'Quiebre de stock en compra PV de Sporting con dos productos dados de baja y alternativas: cambio, reembolso presencial o giftcard-enviada online.',
    compatibleTemplates: ['pim-quiebre-stock-pv'],
  },
  {
    id: 'pim-retiro-disponible-sporting',
    facetas: ['retiro'],
    path: 'examples/pim/shared/retiro-disponible-sporting.json',
    store: 'shared',
    label: 'Sporting (2 productos)',
    tipo: 'PIM — listo para retirar',
    descripcion: 'Pedido listo para retirar en sucursal Sporting, con dos productos, lugar de retiro (dirección y horario) y requisitos.',
    compatibleTemplates: ['pim-retiro-disponible'],
  },
  {
    id: 'pim-giftcard-enviada-sporting',
    path: 'examples/pim/shared/giftcard-enviada-sporting.json',
    store: 'shared',
    label: 'Con saldo y observaciones',
    tipo: 'PIM — giftcard-enviada',
    descripcion: 'Giftcard/código de cambio con código destacado, saldo inicial y observaciones; header dinámico por proveedor.',
    compatibleTemplates: ['pim-giftcard-enviada'],
  },
  {
    id: 'pim-recepcion-cambio-sporting',
    path: 'examples/pim/shared/recepcion-cambio-sporting.json',
    store: 'shared',
    label: 'Aceptado + rechazado',
    tipo: 'PIM — recepción de cambio',
    descripcion: 'Recepción de cambio con un producto aceptado y uno rechazado (con motivo).',
    compatibleTemplates: ['pim-recepcion-cambio'],
  },
  {
    id: 'pim-recepcion-devolucion-sporting',
    path: 'examples/pim/shared/recepcion-devolucion-sporting.json',
    store: 'shared',
    label: 'Aceptado + rechazado',
    tipo: 'PIM — recepción de devolución',
    descripcion: 'Recepción de devolución con un producto aceptado y uno rechazado (con motivo) e info de reembolso.',
    compatibleTemplates: ['pim-recepcion-devolucion'],
  },
  {
    id: 'pim-recepcion-garantia-sporting',
    path: 'examples/pim/shared/recepcion-garantia-sporting.json',
    store: 'shared',
    label: 'Aceptado + rechazado',
    tipo: 'PIM — recepción de garantía',
    descripcion: 'Recepción de garantía con un producto aceptado y uno rechazado (con motivo) y aclaraciones de reembolso.',
    compatibleTemplates: ['pim-recepcion-garantia'],
  },
  {
    id: 'pim-quiebre-stock-sporting',
    path: 'examples/pim/shared/quiebre-stock-sporting.json',
    store: 'shared',
    label: 'Por error de inventario (2 bajas)',
    tipo: 'PIM — quiebre de stock',
    descripcion: 'Reembolso por error de inventario con dos artículos dados de baja y plazos por medio de pago.',
    compatibleTemplates: ['pim-quiebre-stock'],
  },
  {
    id: 'pim-etiqueta-devolucion-sporting',
    path: 'examples/pim/shared/etiqueta-devolucion-sporting.json',
    store: 'shared',
    label: '2 productos a devolver',
    tipo: 'PIM — etiqueta de devolución',
    descripcion: 'Etiqueta de devolución adjunta con dos productos a retirar a domicilio.',
    compatibleTemplates: ['pim-etiqueta-devolucion'],
  },
  {
    id: 'pim-envio-b2b-venta-deportiva',
    facetas: ['multideposito', 'domicilio'],
    path: 'examples/pim/shared/envio-b2b-venta-deportiva.json',
    store: 'venta-deportiva',
    label: 'Venta Deportiva — orden mayorista (2 packs)',
    tipo: 'PIM — despacho B2B',
    descripcion: 'Orden B2B (Venta Deportiva) confirmada y en preparación, con datos de envío y dos packs mayoristas.',
    compatibleTemplates: ['pim-envio-b2b'],
  },
  {
    id: 'pim-factura-disponible-sporting',
    path: 'examples/pim/shared/factura-disponible-sporting.json',
    store: 'shared',
    label: 'Con N° de pedido',
    tipo: 'PIM — factura disponible',
    descripcion: 'Aviso de factura electrónica disponible/adjunta, con N° de pedido.',
    compatibleTemplates: ['pim-factura-disponible'],
  },
];

const TEMPLATE_TAXONOMY = {
  'pedido-confirmado': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    evento: { id: 'pedido-realizado', label: 'Pedido realizado' },
  },
  'woker-pedido-confirmado': {
    canales: ['b2c'],
    tiendas: ['woker'],
    evento: { id: 'pedido-realizado', label: 'Pedido realizado' },
  },
  'pedido-cancelado': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    evento: { id: 'pedido-cancelado', label: 'Pedido cancelado' },
  },
  'woker-pedido-cancelado': {
    canales: ['b2c'],
    tiendas: ['woker'],
    evento: { id: 'pedido-cancelado', label: 'Pedido cancelado' },
  },
  'pago-aprobado': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    evento: { id: 'pago-aprobado', label: 'Pago aprobado' },
  },
  'woker-pago-aprobado': {
    canales: ['b2c'],
    tiendas: ['woker'],
    evento: { id: 'pago-aprobado', label: 'Pago aprobado' },
  },
  'access-key': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    evento: { id: 'acceso-cuenta', label: 'Acceso a cuenta' },
  },
  'b2b-access-key': {
    canales: ['b2b'],
    tiendas: ['venta-deportiva'],
    evento: { id: 'acceso-cuenta', label: 'Acceso a cuenta' },
  },
  'woker-access-key': {
    canales: ['b2c'],
    tiendas: ['woker'],
    evento: { id: 'acceso-cuenta', label: 'Acceso a cuenta' },
  },
  'back-in-stock': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    evento: { id: 'volvio-a-stock', label: 'Volvio a stock' },
  },
  'woker-back-in-stock': {
    canales: ['b2c'],
    tiendas: ['woker'],
    evento: { id: 'volvio-a-stock', label: 'Volvio a stock' },
  },
  'order-invoiced': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    evento: { id: 'pedido-facturado', label: 'Pedido facturado' },
  },
  'b2b-orden-generada': {
    canales: ['b2b'],
    tiendas: ['venta-deportiva'],
    evento: { id: 'orden-generada', label: 'Orden generada' },
  },
  'pim-pedido-confirmado-pv': {
    canales: ['punto-de-venta'],
    tiendas: [],
    evento: { id: 'compra-realizada-pv', label: 'Compra realizada PV' },
  },
  'pim-quiebre-stock-pv': {
    canales: ['punto-de-venta'],
    tiendas: [],
    evento: { id: 'quiebre-stock-pv', label: 'Sin stock PV' },
  },
  'pim-envio-despachado': {
    canales: ['b2c', 'punto-de-venta', 'ext'],
    tiendas: ['sporting', 'woker', 'seller-adidas'],
    logistica: ['andreani', 'ocasa', 'propia', 'retiro', 'producteca-oca', 'producteca-correo-argentino', 'producteca-trf', 'producteca-urbano'],
    evento: { id: 'pedido-despachado', label: 'Pedido despachado' },
  },
  'pim-retiro-disponible': {
    canales: ['b2c', 'punto-de-venta'],
    tiendas: ['sporting', 'woker'],
    logistica: ['retiro'],
    evento: { id: 'pedido-listo-para-retirar', label: 'Pedido listo para retirar' },
  },
  'pim-envio-b2b': {
    canales: ['b2b'],
    tiendas: ['venta-deportiva'],
    logistica: ['propia'],
    evento: { id: 'envio-b2b', label: 'Despacho B2B' },
  },
  'pim-giftcard-enviada': {
    canales: ['b2c', 'punto-de-venta'],
    tiendas: ['sporting', 'woker'],
    evento: { id: 'giftcard-enviada', label: 'Giftcard' },
  },
  'pim-recepcion-cambio': {
    canales: ['b2c', 'punto-de-venta'],
    tiendas: ['sporting', 'woker'],
    evento: { id: 'recepcion-cambio', label: 'Recepcion de cambio' },
  },
  'pim-recepcion-devolucion': {
    canales: ['b2c'],
    tiendas: ['sporting', 'woker'],
    evento: { id: 'recepcion-devolucion', label: 'Recepcion de devolucion' },
  },
  'pim-recepcion-garantia': {
    canales: ['b2c', 'punto-de-venta'],
    tiendas: ['sporting', 'woker'],
    evento: { id: 'recepcion-garantia', label: 'Recepcion de garantia' },
  },
  'pim-quiebre-stock': {
    canales: ['b2c'],
    tiendas: ['sporting', 'woker'],
    evento: { id: 'quiebre-stock', label: 'Quiebre de stock' },
  },
  'pim-factura-disponible': {
    canales: ['b2c'],
    tiendas: ['sporting', 'woker'],
    evento: { id: 'factura-disponible', label: 'Factura disponible' },
  },
  'pim-etiqueta-devolucion': {
    canales: ['b2c', 'punto-de-venta'],
    tiendas: ['sporting', 'woker'],
    evento: { id: 'etiqueta-devolucion', label: 'Etiqueta de devolucion' },
  },
};

const SCENARIO_TAXONOMY = {
  'pim-envio-despachado-andreani': {
    canales: ['b2c', 'punto-de-venta'],
    tiendas: ['sporting', 'woker'],
    logistica: ['andreani'],
    eventoId: 'pedido-despachado',
  },
  'pim-envio-despachado-ocasa': {
    canales: ['b2c'],
    tiendas: ['sporting', 'woker'],
    logistica: ['ocasa'],
    eventoId: 'pedido-despachado',
  },
  'pim-envio-despachado-propia': {
    canales: ['b2c'],
    tiendas: ['sporting', 'woker'],
    logistica: ['propia'],
    eventoId: 'pedido-despachado',
  },
  'pim-envio-despachado-producteca-oca': {
    canales: ['ext'],
    tiendas: ['seller-adidas'],
    logistica: ['producteca-oca'],
    eventoId: 'pedido-despachado',
  },
  'pim-envio-despachado-producteca-correo-argentino': {
    canales: ['ext'],
    tiendas: ['seller-adidas'],
    logistica: ['producteca-correo-argentino'],
    eventoId: 'pedido-despachado',
  },
  'pim-envio-despachado-producteca-trf': {
    canales: ['ext'],
    tiendas: ['seller-adidas'],
    logistica: ['producteca-trf'],
    eventoId: 'pedido-despachado',
  },
  'pim-envio-despachado-producteca-urbano': {
    canales: ['ext'],
    tiendas: ['seller-adidas'],
    logistica: ['producteca-urbano'],
    eventoId: 'pedido-despachado',
  },
  'pim-envio-despachado-producteca-sin-tracking': {
    canales: ['ext'],
    tiendas: ['seller-adidas'],
    eventoId: 'pedido-despachado',
  },
  'pim-pedido-confirmado-pv-sporting': {
    canales: ['punto-de-venta'],
    tiendas: [],
    eventoId: 'compra-realizada-pv',
  },
  'pim-pedido-confirmado-pv-woker': {
    canales: ['punto-de-venta'],
    tiendas: [],
    eventoId: 'compra-realizada-pv',
  },
  'pim-quiebre-stock-pv-sporting': {
    canales: ['punto-de-venta'],
    tiendas: [],
    eventoId: 'quiebre-stock-pv',
  },
  'pim-retiro-disponible-sporting': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    logistica: ['retiro'],
    eventoId: 'pedido-listo-para-retirar',
  },
  'pim-giftcard-enviada-sporting': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    eventoId: 'giftcard-enviada',
  },
  'pim-recepcion-cambio-sporting': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    eventoId: 'recepcion-cambio',
  },
  'pim-recepcion-devolucion-sporting': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    eventoId: 'recepcion-devolucion',
  },
  'pim-recepcion-garantia-sporting': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    eventoId: 'recepcion-garantia',
  },
  'pim-quiebre-stock-sporting': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    eventoId: 'quiebre-stock',
  },
  'pim-etiqueta-devolucion-sporting': {
    canales: ['b2c'],
    tiendas: ['sporting'],
    eventoId: 'etiqueta-devolucion',
  },
  'pim-envio-b2b-venta-deportiva': {
    canales: ['b2b'],
    tiendas: ['venta-deportiva'],
    logistica: ['propia'],
    eventoId: 'envio-b2b',
  },
};

const EVENT_STAGE_META = {
  'acceso-cuenta': { id: 'cuenta-acceso', label: 'Cuenta / Acceso' },
  'volvio-a-stock': { id: 'cuenta-acceso', label: 'Cuenta / Acceso' },
  'pedido-realizado': { id: 'compra-pedido', label: 'Compra o Pedido realizado' },
  'orden-generada': { id: 'compra-pedido', label: 'Compra o Pedido realizado' },
  'compra-realizada-pv': { id: 'compra-pedido', label: 'Compra o Pedido realizado' },
  'pago-aprobado': { id: 'pago', label: 'Pago' },
  'pedido-facturado': { id: 'facturacion', label: 'Facturacion' },
  'factura-disponible': { id: 'facturacion', label: 'Facturacion' },
  'pedido-despachado': { id: 'despacho-retiro', label: 'Despacho / Retiro' },
  'pedido-listo-para-retirar': { id: 'despacho-retiro', label: 'Despacho / Retiro' },
  'envio-b2b': { id: 'preparacion', label: 'Preparacion' },
  'pedido-cancelado': { id: 'cancelacion-reembolso', label: 'Cancelacion / Reembolso' },
  'quiebre-stock-pv': { id: 'cancelacion-reembolso', label: 'Cancelacion / Reembolso' },
  'quiebre-stock': { id: 'cancelacion-reembolso', label: 'Cancelacion / Reembolso' },
  'etiqueta-devolucion': { id: 'cambios-devoluciones-garantia', label: 'Cambios / Devoluciones / Garantia' },
  'recepcion-cambio': { id: 'cambios-devoluciones-garantia', label: 'Cambios / Devoluciones / Garantia' },
  'recepcion-devolucion': { id: 'cambios-devoluciones-garantia', label: 'Cambios / Devoluciones / Garantia' },
  'recepcion-garantia': { id: 'cambios-devoluciones-garantia', label: 'Cambios / Devoluciones / Garantia' },
  'giftcard-enviada': { id: 'cambios-devoluciones-garantia', label: 'Cambios / Devoluciones / Garantia' },
};

function uniqueTaxonomyValues(values) {
  return Array.from(new Set((values || []).filter(Boolean)));
}

function normalizeTaxonomyArray(values) {
  return uniqueTaxonomyValues(Array.isArray(values) ? values : [values]);
}

function taxonomyFromTemplates(templateIds, field) {
  return uniqueTaxonomyValues((templateIds || []).flatMap((templateId) => {
    const template = TEMPLATES.find((item) => item.id === templateId);
    const fallback = TEMPLATE_TAXONOMY[templateId] || {};
    return (template && template[field]) || fallback[field] || [];
  }));
}

TEMPLATES.forEach((template) => {
  const taxonomy = TEMPLATE_TAXONOMY[template.id] || {};
  template.canales = normalizeTaxonomyArray(template.canales || taxonomy.canales || ['b2c']);
  template.tiendas = normalizeTaxonomyArray(template.tiendas || taxonomy.tiendas || template.tienda || template.store);
  template.logistica = normalizeTaxonomyArray(template.logistica || taxonomy.logistica || []);
  template.evento = template.evento || taxonomy.evento || { id: template.id, label: template.nombre };
  const stage = EVENT_STAGE_META[template.evento.id] || { id: 'sin-etapa', label: 'Sin etapa normalizada' };
  template.stageId = template.stageId || stage.id;
  template.stageLabel = template.stageLabel || stage.label;
});

EXAMPLE_SCENARIOS.forEach((scenario) => {
  const taxonomy = SCENARIO_TAXONOMY[scenario.id] || {};
  scenario.canales = normalizeTaxonomyArray(
    scenario.canales || taxonomy.canales || taxonomyFromTemplates(scenario.compatibleTemplates, 'canales')
  );
  scenario.tiendas = normalizeTaxonomyArray(
    scenario.tiendas || taxonomy.tiendas || taxonomyFromTemplates(scenario.compatibleTemplates, 'tiendas') || scenario.tienda || scenario.store
  );
  // La logística es específica del escenario (un carrier), no se hereda de la plantilla.
  scenario.logistica = normalizeTaxonomyArray(scenario.logistica || taxonomy.logistica || []);
  scenario.eventoId = scenario.eventoId
    || taxonomy.eventoId
    || (scenario.compatibleTemplates || [])
      .map((templateId) => {
        const template = TEMPLATES.find((item) => item.id === templateId);
        return template && template.evento && template.evento.id;
      })
      .find(Boolean)
    || scenario.tipo;
  const stage = EVENT_STAGE_META[scenario.eventoId] || { id: 'sin-etapa', label: 'Sin etapa normalizada' };
  scenario.stageId = scenario.stageId || stage.id;
  scenario.stageLabel = scenario.stageLabel || stage.label;
});

const VERSION = {
  number: '1.17.0',
  date: '2026-06-11',
  summary: 'Facetas de escenario (paquetes, promoción, envío, entrega) con filtros en el Visualizador.',
};

const CHANGELOG = [
  { version: '1.17.0', date: '2026-06-11', summary: 'Facetas de escenario (paquetes, promoción, envío, entrega): etiquetado por escenario, filtros multi-grupo en el Visualizador y badges. Promoción pendiente de datos.' },
  { version: '1.16.0', date: '2026-06-11', summary: 'Modelo canal/tienda/logística: 4 canales (PV/B2C/B2B/EXT), Venta Deportiva como tienda B2B, Seller adidas/Producteca como EXT, y filtro de Logística en los módulos.' },
  { version: '1.15.0', date: '2026-06-11', summary: 'Plantilla PIM Sin stock PV, escenario Sporting representativo y flujo actualizado para Punto de Venta.' },
  { version: '1.4.0', date: '2026-06-09', summary: 'Inventario PIM, 14 plantillas compartidas en catálogo, renderer PIM mínimo y envio-despachado v2 con escenario representativo.' },
  { version: '1.3.0', date: '2026-06-08', summary: 'Nueva plantilla orden generada B2B y escenario específico para previsualización.' },
  { version: '0.7.0', date: '2026-06-07', summary: 'Flujo de Correos suma estados por nodo, ficha operativa, acciones para previsualización/creación y soporte de query params en Visualizador.' },
  { version: '0.6.0', date: '2026-06-06', summary: 'Módulo Flujo de Correos con mapa por pestañas para entrega, cambio, devolución y garantía, organizado por plataforma.' },
  { version: '0.5.0', date: '2026-06-06', summary: 'Se priorizan Biblioteca y Visualizador como flujo principal; Simulador queda rotulado como QA interno y se documenta el flujo para crear nuevas plantillas con JSON representativo.' },
  { version: '0.4.0', date: '2026-06-06', summary: 'Datos de ejemplo sanitizados, Handlebars local, escenarios centralizados, simulador coherente en multipaquete y docs de validación/roadmap.' },
  { version: '0.3.0', date: '2026-06-06', summary: 'Simulador de Datos (Módulo 4) con escenarios combinables; fix: normalización de pedidos "desnudos" en el render compartido.' },
  { version: '0.2.0', date: '2026-06-06', summary: 'Visualizador de Plantillas (Módulo 3) con selector de plantilla y escenario, render con Handlebars.' },
  { version: '0.1.0', date: '2026-06-06', summary: 'Estructura inicial y catálogo con pedido-confirmado y pago-aprobado.' },
];
