/**
 * Catálogo de plantillas de Correos Transaccionales.
 *
 * Esquema de cada entrada (Módulo 2 — Biblioteca de Plantillas):
 *   id            -> identificador único, kebab-case, igual al nombre de archivo sin extensión
 *   nombre        -> nombre visible de la plantilla
 *   plataforma    -> "VTEX" | "PIM" | otra plataforma futura
 *   categoria     -> etapa del flujo (ver modules/flujo): "Logística de Entrega",
 *                    "Logística inversa - Cambio", "Logística inversa - Devolución",
 *                    "Logística inversa - Garantía"
 *   estado        -> "activo" | "en revisión" | "deprecado"
 *   actualizado   -> fecha de última actualización (YYYY-MM-DD)
 *   responsable   -> dueño/a funcional de la plantilla
 *   descripcion   -> qué dispara el envío y a quién
 *   archivoHtml   -> ruta relativa al HTML real dentro de templates/
 *   ejemplo       -> ruta relativa al JSON de datos de ejemplo dentro de examples/ (puede ser null si aún no hay)
 *   variables     -> lista de variables/datos clave que usa la plantilla (para consulta rápida,
 *                    no es la lista exhaustiva de helpers Handlebars del HTML)
 *
 * EXAMPLE_SCENARIOS centraliza los JSON disponibles para previsualización.
 *   id                  -> identificador estable del escenario
 *   path                -> ruta relativa al JSON dentro de examples/
 *   label               -> nombre visible del escenario
 *   tipo                -> familia funcional del JSON
 *   descripcion         -> variante que representa
 *   compatibleTemplates -> ids de plantillas que pueden renderizarse con ese JSON
 */

const TEMPLATES = [
  {
    id: 'pedido-confirmado',
    nombre: 'Pedido realizado con éxito',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'activo',
    actualizado: '2026-06-06',
    responsable: 'Por definir',
    descripcion: 'Confirma al cliente que su pedido fue registrado correctamente, con resumen de productos, totales, dirección y forma de pago.',
    archivoHtml: 'templates/vtex/sporting/pedido-confirmado/pedido-confirmado.v2.html',
    ejemplo: 'examples/vtex/sporting/pedido-estandar.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orders.0.orderId',
      'orders.0.creationDate',
      'orders.0.clientProfileData.firstName',
      'orders.0.value (formatCurrency)',
      'orders.0.items[] (skuName, quantity, listPrice, sellingPrice, imageUrl)',
      'orders.0.totals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'orders.0.shippingData.selectedAddresses[0] (street, number, complement, city, state, postalCode)',
      'orders.0.shippingData.logisticsInfo[0].deliveryIds[0].courierName',
      'orders.0.paymentData.transactions[].payments[] (paymentSystemName, installments, lastDigits, connectorResponses.authId)',
      'orders.0.ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
      'orders.0.items[] (imageUrl, detailUrl — usados en links de producto)',
    ],
  },
  {
    id: 'woker-pedido-confirmado',
    nombre: 'Pedido realizado Woker',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma al cliente Woker que su pedido fue registrado correctamente, con resumen de productos, totales, dirección y forma de pago.',
    archivoHtml: 'templates/vtex/woker/pedido-confirmado/pedido-confirmado.v2.html',
    ejemplo: 'examples/vtex/woker/pedido-estandar.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orders.0.orderId',
      'orders.0.creationDate',
      'orders.0.clientProfileData.firstName',
      'orders.0.value (formatCurrency)',
      'orders.0.items[] (skuName, quantity, listPrice, sellingPrice, imageUrl)',
      'orders.0.totals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'orders.0.shippingData.selectedAddresses[0] (street, number, complement, city, state, postalCode)',
      'orders.0.shippingData.logisticsInfo[0].deliveryIds[0].courierName',
      'orders.0.paymentData.transactions[].payments[] (paymentSystemName, installments, lastDigits, connectorResponses.authId)',
      'orders.0.ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
      'orders.0.items[] (imageUrl, detailUrl — usados en links de producto)',
    ],
  },
  {
    id: 'pedido-cancelado',
    nombre: 'Pedido cancelado',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'activo',
    actualizado: '2026-06-08',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que su pedido fue cancelado e informa el proceso de reintegro según el medio de pago.',
    archivoHtml: 'templates/vtex/sporting/pedido-cancelado/pedido-cancelado.v2.html',
    ejemplo: 'examples/vtex/sporting/pedido-cancelado.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orderId',
      'creationDate',
      'clientProfileData.firstName',
      'value (formatCurrency)',
      'cancellationData.cancellationDate',
      'cancellationData.reason',
      'items[] (name, skuName, brandName, quantity, listPrice, sellingPrice, imageUrl, priceDefinition.total)',
      'totals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'shippingData.selectedAddresses[0] (receiverName, street, number, city, state, postalCode)',
      'shippingData.logisticsInfo[0].selectedDeliveryChannel',
      'paymentData.transactions[].payments[] (paymentSystemName, value, installments, lastDigits, group, connectorResponses.authId)',
      'ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
    ],
  },
  {
    id: 'woker-pedido-cancelado',
    nombre: 'Pedido cancelado Woker',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente Woker que su pedido fue cancelado e informa el proceso de reintegro según el medio de pago.',
    archivoHtml: 'templates/vtex/woker/pedido-cancelado/pedido-cancelado.v2.html',
    ejemplo: 'examples/vtex/woker/pedido-cancelado.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orderId',
      'creationDate',
      'clientProfileData.firstName',
      'value (formatCurrency)',
      'cancellationData.cancellationDate',
      'cancellationData.reason',
      'items[] (name, skuName, brandName, quantity, listPrice, sellingPrice, imageUrl, priceDefinition.total)',
      'totals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'shippingData.selectedAddresses[0] (receiverName, street, number, city, state, postalCode)',
      'shippingData.logisticsInfo[0].selectedDeliveryChannel',
      'paymentData.transactions[].payments[] (paymentSystemName, value, installments, lastDigits, group, connectorResponses.authId)',
      'ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
    ],
  },
  {
    id: 'pago-aprobado',
    nombre: 'Pago aprobado',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'activo',
    actualizado: '2026-06-06',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que el pago de su pedido fue aprobado, con resumen de productos, totales, envío/retiro y forma de pago.',
    archivoHtml: 'templates/vtex/sporting/pago-aprobado/pago-aprobado.v2.html',
    ejemplo: 'examples/vtex/sporting/pedido-estandar.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orderId',
      'creationDate',
      'clientProfileData.firstName',
      'items[] (skuName, quantity, listPrice, sellingPrice, imageUrl, detailUrl)',
      'totals[] / alternativeTotals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'shippingData.selectedAddresses[0] (street, number, complement, city, state, postalCode)',
      'shippingData.logisticsInfo[] (selectedDeliveryChannel, shippingEstimateDate, deliveryIds[0].courierName)',
      'paymentData.transactions[].payments[] (paymentSystemName, installments, lastDigits, connectorResponses.authId)',
      'ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
    ],
  },
  {
    id: 'woker-pago-aprobado',
    nombre: 'Pago aprobado Woker',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente Woker que el pago de su pedido fue aprobado, con resumen de productos, totales, envío/retiro y forma de pago.',
    archivoHtml: 'templates/vtex/woker/pago-aprobado/pago-aprobado.v2.html',
    ejemplo: 'examples/vtex/woker/pago-aprobado.sample.json',
    variables: [
      'hostName',
      '_accountInfo.TradingName',
      'orderId',
      'creationDate',
      'clientProfileData.firstName',
      'items[] (skuName, quantity, listPrice, sellingPrice, imageUrl, detailUrl)',
      'totals[] / alternativeTotals[] (Items, Discounts, Shipping, Tax, GiftCards)',
      'shippingData.selectedAddresses[0] (street, number, complement, city, state, postalCode)',
      'shippingData.logisticsInfo[] (selectedDeliveryChannel, shippingEstimateDate, deliveryIds[0].courierName)',
      'paymentData.transactions[].payments[] (paymentSystemName, installments, lastDigits, connectorResponses.authId)',
      'ratesAndBenefitsData.rateAndBenefitsIdentifiers[] (name, description)',
    ],
  },
  {
    id: 'access-key',
    nombre: 'Código de acceso a cuenta',
    plataforma: 'VTEX',
    categoria: 'Cuenta',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Envía un código de verificación al cliente cuando solicita ingresar o recuperar acceso a su cuenta.',
    archivoHtml: 'templates/vtex/sporting/access-key/access-key.v2.html',
    ejemplo: 'examples/vtex/sporting/access-key.sample.json',
    variables: [
      'to[0].name',
      'aditionalData.accessKey',
      'aditionalData.userAgent',
      '_accountInfo.TradingName',
      '_accountInfo.AccountName',
      '_accountInfo.HostName',
    ],
  },
  {
    id: 'b2b-access-key',
    nombre: 'Código de acceso B2B',
    plataforma: 'VTEX',
    categoria: 'Cuenta',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Envía un código de verificación al comprador B2B cuando solicita ingresar a su cuenta.',
    archivoHtml: 'templates/vtex/b2b/access-key/access-key.v2.html',
    ejemplo: 'examples/vtex/sporting/access-key.sample.json',
    variables: [
      'to[0].name',
      'aditionalData.accessKey',
      'aditionalData.userAgent',
      '_accountInfo.TradingName',
      '_accountInfo.AccountName',
      '_accountInfo.HostName',
    ],
  },
  {
    id: 'woker-access-key',
    nombre: 'Código de acceso Woker',
    plataforma: 'VTEX',
    categoria: 'Cuenta',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Envía un código de verificación al cliente Woker cuando solicita ingresar o recuperar acceso a su cuenta.',
    archivoHtml: 'templates/vtex/woker/access-key/access-key.v2.html',
    ejemplo: 'examples/vtex/woker/access-key.sample.json',
    variables: [
      'to[0].name',
      'aditionalData.accessKey',
      'aditionalData.userAgent',
      '_accountInfo.TradingName',
      '_accountInfo.AccountName',
      '_accountInfo.HostName',
    ],
  },
  {
    id: 'back-in-stock',
    nombre: 'Volvió a stock',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente suscrito que un SKU sin stock volvió a estar disponible para comprar.',
    archivoHtml: 'templates/vtex/sporting/back-in-stock/back-in-stock.v2.html',
    ejemplo: 'examples/vtex/sporting/back-in-stock.sample.json',
    variables: [
      'NotifyRequest.name',
      'NotifyRequest.locale',
      'NotifyRequest.seller.addToCartLink',
      'SkuContext.NameComplete',
      'SkuContext.ProductName',
      'SkuContext.SkuName',
      'SkuContext.ImageUrl',
      'SkuContext.DetailUrl',
      '_accountInfo.TradingName',
    ],
  },
  {
    id: 'woker-back-in-stock',
    nombre: 'Volvió a stock Woker',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente Woker suscrito que un SKU sin stock volvió a estar disponible para comprar.',
    archivoHtml: 'templates/vtex/woker/back-in-stock/back-in-stock.v2.html',
    ejemplo: 'examples/vtex/woker/back-in-stock.sample.json',
    variables: [
      'NotifyRequest.name',
      'NotifyRequest.locale',
      'NotifyRequest.seller.addToCartLink',
      'SkuContext.NameComplete',
      'SkuContext.ProductName',
      'SkuContext.SkuName',
      'SkuContext.Images[0].ImageUrl / SkuContext.ImageUrl',
      'SkuContext.DetailUrl',
      '_accountInfo.TradingName',
    ],
  },
  {
    id: 'order-invoiced',
    nombre: 'Pedido facturado',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que su pedido fue facturado, con acceso a las facturas y datos de seguimiento del despacho.',
    archivoHtml: 'templates/vtex/sporting/order-invoiced/order-invoiced.v2.html',
    ejemplo: 'examples/vtex/sporting/order-invoiced.sample.json',
    variables: [
      'orderId',
      'clientProfileData.firstName',
      'hostName / _accountInfo.HostName',
      '_accountInfo.TradingName',
      'packages[] (invoiceNumber, invoiceValue, invoiceUrl, issuanceDate, courier, trackingNumber, trackingUrl)',
      'package.* (fallback cuando no hay packages[])',
      'shippingData.address (street, number, city, state, country)',
      'paymentData.transactions[].payments[] (paymentSystemName, installments)',
    ],
  },
  {
    id: 'b2b-orden-generada',
    nombre: 'Orden generada B2B',
    plataforma: 'VTEX',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma a un comprador B2B que la orden fue generada y queda pendiente de validación comercial antes de avanzar al resto del flujo.',
    archivoHtml: 'templates/vtex/b2b/orden-generada/orden-generada.v2.html',
    ejemplo: 'examples/vtex/b2b/orden-generada.sample.json',
    variables: [
      '_accountInfo.TradingName',
      'ordersUrl',
      'orderId',
      'creationDate',
      'clientProfileData.firstName / lastName / email / document',
      'value (formatCurrency)',
      'items[] (name, skuName, quantity, sellingPrice, priceDefinition.total, imageUrl, detailUrl)',
      'subjectItemAttachment.totalItems',
      'totals[] (Items, Discounts, Shipping, Tax)',
      'shippingData.selectedAddresses[0] / shippingData.address',
      'shippingData.logisticsInfo[0] (selectedDeliveryChannel, shippingEstimateDate)',
      'paymentData.transactions[].payments[] (paymentSystemName, group, value, installments)',
    ],
  },
  {
    id: 'pim-nuevo-envio',
    nombre: 'Nuevo envío',
    plataforma: 'PIM',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que su pedido fue despachado e informa operador logistico, numero de seguimiento y proximo paso.',
    archivoHtml: 'templates/pim/shared/nuevo-envio/nuevo-envio.v2.html',
    ejemplo: 'examples/pim/shared/nuevo-envio.sample.json',
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.DatosEnvio.Destinatario.Nombres',
      'Pedido.Logistica',
      'Pedido.DatosEnvio.Etiqueta.NroSeguimiento',
    ],
  },
  {
    id: 'pim-nuevo-pickup',
    nombre: 'Nuevo pickup',
    plataforma: 'PIM',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Informa al cliente que su pedido ya esta disponible para retiro en la sucursal seleccionada.',
    archivoHtml: 'templates/pim/shared/nuevo-pickup/nuevo-pickup.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[0].Deposito',
    ],
  },
  {
    id: 'pim-despacho-pickup',
    nombre: 'Despacho pickup',
    plataforma: 'PIM',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma el despacho de un pedido con retiro en pickup, con resumen de orden, productos y lugar de retiro.',
    archivoHtml: 'templates/pim/shared/despacho-pickup/despacho-pickup.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.FechaPedido',
      'Pedido.LineasPedido[] (Producto, SKU, Importe, Cantidad, Subtotal)',
      'Pedido.TotalLineas',
      'Deposito.DatosDeposito.DatosPickup (NombrePublico, Direccion, Localidad, Horario)',
    ],
  },
  {
    id: 'pim-despacho-b2b',
    nombre: 'Despacho B2B',
    plataforma: 'PIM',
    categoria: 'Logística de Entrega',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma el despacho de una orden B2B, con datos de envio, productos y totales.',
    archivoHtml: 'templates/pim/shared/despacho-b2b/despacho-b2b.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.FechaPedido',
      'Pedido.DatosEnvio.Destino.Postal (Calle, Numero, Localidad, Pais, CodigoPostal, Referencia)',
      'Pedido.LineasPedido[] (Producto, SKU, Importe, Cantidad, Subtotal)',
      'Pedido.TotalLineas',
    ],
  },
  {
    id: 'pim-giftcard',
    nombre: 'Giftcard',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Cambio',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Informa la emision de una giftcard para resolver un cambio, devolucion o incidencia de stock.',
    archivoHtml: 'templates/pim/shared/giftcard/giftcard.current.html',
    ejemplo: null,
    variables: [
      'Proveedor.GetEmailHeaderURL',
      'Proveedor.GetEmailHeaderImage',
      'Giftcard.Codigo',
      'Giftcard.SaldoInicial',
      'Giftcard.Descripcion',
    ],
  },
  {
    id: 'pim-recepcion-cambio',
    nombre: 'Recepcion de cambio',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Cambio',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma la recepcion de productos vinculados a un cambio e informa estados aceptados o rechazados.',
    archivoHtml: 'templates/pim/shared/recepcion-cambio/recepcion-cambio.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[] (Producto, SKU, Cantidad, Estado)',
      'LineasPedido[].Historial[0].Observaciones',
    ],
  },
  {
    id: 'pim-recepcion-devolucion',
    nombre: 'Recepcion de devolucion',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Devolución',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma la recepcion de productos devueltos y comunica el avance del reintegro o revision.',
    archivoHtml: 'templates/pim/shared/recepcion-devolucion/recepcion-devolucion.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[] (Producto, SKU, Cantidad, Estado)',
      'LineasPedido[].Historial[0].Observaciones',
    ],
  },
  {
    id: 'pim-recepcion-garantia',
    nombre: 'Recepcion de garantia',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Garantía',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Confirma la recepcion de un producto asociado a garantia e informa estados de aceptacion o rechazo.',
    archivoHtml: 'templates/pim/shared/recepcion-garantia/recepcion-garantia.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[] (Producto, SKU, Cantidad, Estado)',
      'LineasPedido[].Historial[0].Observaciones',
    ],
  },
  {
    id: 'pim-reembolso',
    nombre: 'Reembolso',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Devolución',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Informa que se gestiono el reembolso por productos no procesados o dados de baja.',
    archivoHtml: 'templates/pim/shared/reembolso/reembolso.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.NroPedidoCanal',
      'Pedido.LineasPedido[] (Producto, SKU, Cantidad, Estado)',
    ],
  },
  {
    id: 'pim-factura-disponible',
    nombre: 'Factura disponible',
    plataforma: 'PIM',
    categoria: 'Facturación',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Notifica al cliente que su factura ya esta disponible.',
    archivoHtml: 'templates/pim/shared/factura-disponible/factura-disponible.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
    ],
  },
  {
    id: 'pim-etiqueta-devolucion',
    nombre: 'Etiqueta de devolucion',
    plataforma: 'PIM',
    categoria: 'Logística inversa - Devolución',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Informa al cliente los productos incluidos en una etiqueta de devolucion.',
    archivoHtml: 'templates/pim/shared/etiqueta-devolucion/etiqueta-devolucion.current.html',
    ejemplo: null,
    variables: [
      'Tienda.Datos.NotificacionesConfig.HeaderURL',
      'Tienda.Datos.NotificacionesConfig.HeaderImage',
      'Pedido.LineasPedido[] (Producto, SKU, Cantidad)',
    ],
  },
  {
    id: 'pim-andreani-alta-automatica',
    nombre: 'Andreani alta automatica',
    plataforma: 'PIM',
    categoria: 'Andreani',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Correo simple con numero de seguimiento de Andreani. Requiere confirmar si pertenece al estandar PIM o al frente logistico Andreani.',
    archivoHtml: 'templates/pim/shared/andreani-alta-automatica/andreani-alta-automatica.current.html',
    ejemplo: null,
    variables: [
      'NroSeguimiento',
    ],
  },
  {
    id: 'pim-andreani-distribucion',
    nombre: 'Andreani distribucion',
    plataforma: 'PIM',
    categoria: 'Andreani',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Correo simple de distribucion con numero de seguimiento de Andreani. Requiere normalizar alcance.',
    archivoHtml: 'templates/pim/shared/andreani-distribucion/andreani-distribucion.current.html',
    ejemplo: null,
    variables: [
      'NroSeguimiento',
    ],
  },
  {
    id: 'pim-andreani-entregado',
    nombre: 'Andreani entregado',
    plataforma: 'PIM',
    categoria: 'Andreani',
    estado: 'en revisión',
    actualizado: '2026-06-09',
    responsable: 'Por definir',
    descripcion: 'Correo simple de entrega con numero de seguimiento de Andreani. Requiere confirmar si se redisena dentro de PIM.',
    archivoHtml: 'templates/pim/shared/andreani-entregado/andreani-entregado.current.html',
    ejemplo: null,
    variables: [
      'NroSeguimiento',
    ],
  },
];

const EXAMPLE_SCENARIOS = [
  {
    id: 'pedido-estandar-domicilio',
    path: 'examples/vtex/sporting/pedido-estandar.sample.json',
    label: 'Pedido estándar - envío a domicilio',
    tipo: 'Pedido',
    descripcion: 'Pedido confirmado con varios productos, totales, dirección de entrega y pago registrado.',
    compatibleTemplates: ['pedido-confirmado', 'pago-aprobado'],
  },
  {
    id: 'pedido-estandar-woker',
    path: 'examples/vtex/woker/pedido-estandar.sample.json',
    label: 'Woker - pedido estándar',
    tipo: 'Pedido',
    descripcion: 'Pedido Woker confirmado con varios productos, totales, dirección de entrega y pago registrado.',
    compatibleTemplates: ['woker-pedido-confirmado'],
  },
  {
    id: 'pedido-realizado-exito',
    path: 'examples/vtex/sporting/pedido-realizado.sample.json',
    label: 'Pedido realizado - 1 producto',
    tipo: 'Pedido',
    descripcion: 'Pedido confirmado simple para validar la rama base de compra realizada.',
    compatibleTemplates: ['pedido-confirmado', 'pago-aprobado'],
  },
  {
    id: 'pago-aprobado-base',
    path: 'examples/vtex/sporting/pago-aprobado.sample.json',
    label: 'Pago aprobado - pedido base',
    tipo: 'Pedido',
    descripcion: 'Pedido con pago aprobado, datos de medio de pago y logística de entrega.',
    compatibleTemplates: ['pago-aprobado', 'pedido-confirmado'],
  },
  {
    id: 'pago-aprobado-woker',
    path: 'examples/vtex/woker/pago-aprobado.sample.json',
    label: 'Woker - pago aprobado',
    tipo: 'Pedido',
    descripcion: 'Pedido Woker con pago aprobado, datos de medio de pago y logística de entrega.',
    compatibleTemplates: ['woker-pago-aprobado'],
  },
  {
    id: 'pedido-cancelado-un-producto',
    path: 'examples/vtex/sporting/pedido-cancelado.sample.json',
    label: 'Cancelación - 1 producto',
    tipo: 'Cancelación',
    descripcion: 'Pedido cancelado con reintegro y un producto en el resumen.',
    compatibleTemplates: ['pedido-cancelado'],
  },
  {
    id: 'pedido-cancelado-woker',
    path: 'examples/vtex/woker/pedido-cancelado.sample.json',
    label: 'Woker - pedido cancelado',
    tipo: 'Cancelación',
    descripcion: 'Pedido Woker cancelado con reintegro y productos en el resumen.',
    compatibleTemplates: ['woker-pedido-cancelado'],
  },
  {
    id: 'pedido-cancelado-envio-gratis',
    path: 'examples/vtex/sporting/pedido-cancelado-2.sample.json',
    label: 'Cancelación - 2 productos, envío gratis',
    tipo: 'Cancelación',
    descripcion: 'Pedido cancelado con más de un producto y condición de envío bonificado.',
    compatibleTemplates: ['pedido-cancelado'],
  },
  {
    id: 'access-key-login',
    path: 'examples/vtex/sporting/access-key.sample.json',
    store: 'shared',
    label: 'Acceso a cuenta - código de ingreso',
    tipo: 'Cuenta',
    descripcion: 'Evento de login o recuperación con código de verificación.',
    compatibleTemplates: ['access-key', 'b2b-access-key'],
  },
  {
    id: 'access-key-woker',
    path: 'examples/vtex/woker/access-key.sample.json',
    label: 'Woker - acceso a cuenta',
    tipo: 'Cuenta',
    descripcion: 'Evento de login o recuperación de Woker con código de verificación.',
    compatibleTemplates: ['woker-access-key'],
  },
  {
    id: 'back-in-stock-disponible',
    path: 'examples/vtex/sporting/back-in-stock.sample.json',
    label: 'Stock - SKU disponible',
    tipo: 'Stock',
    descripcion: 'Aviso a cliente suscrito cuando un SKU vuelve a estar disponible.',
    compatibleTemplates: ['back-in-stock'],
  },
  {
    id: 'back-in-stock-woker',
    path: 'examples/vtex/woker/back-in-stock.sample.json',
    label: 'Woker - SKU disponible',
    tipo: 'Stock',
    descripcion: 'Aviso a cliente Woker suscrito cuando un SKU vuelve a estar disponible.',
    compatibleTemplates: ['woker-back-in-stock'],
  },
  {
    id: 'order-invoiced-seguimiento',
    path: 'examples/vtex/sporting/order-invoiced.sample.json',
    label: 'Facturación - con seguimiento',
    tipo: 'Facturación',
    descripcion: 'Pedido facturado con paquete, factura y datos de tracking.',
    compatibleTemplates: ['order-invoiced'],
  },
  {
    id: 'b2b-orden-generada-base',
    path: 'examples/vtex/b2b/orden-generada.sample.json',
    label: 'B2B - orden generada',
    tipo: 'B2B',
    descripcion: 'Orden B2B recibida con pago a validar, varios productos y entrega a domicilio.',
    compatibleTemplates: ['b2b-orden-generada'],
  },
  {
    id: 'pim-nuevo-envio-andreani',
    path: 'examples/pim/shared/nuevo-envio.sample.json',
    store: 'shared',
    label: 'Andreani',
    tipo: 'PIM — nuevo envío',
    descripcion: 'Despacho por Andreani con número de seguimiento activo. Link directo al tracking.',
    compatibleTemplates: ['pim-nuevo-envio'],
  },
  {
    id: 'pim-nuevo-envio-producteca-urbano',
    path: 'examples/pim/shared/nuevo-envio-producteca-urbano.json',
    store: 'shared',
    label: 'Producteca → Urbano (UR…)',
    tipo: 'PIM — nuevo envío',
    descripcion: 'Despacho por Producteca con tracking Urbano (prefijo UR). Muestra "Urbano" como carrier real.',
    compatibleTemplates: ['pim-nuevo-envio'],
  },
  {
    id: 'pim-nuevo-envio-producteca-correo-argentino',
    path: 'examples/pim/shared/nuevo-envio-producteca-correo-argentino.json',
    store: 'shared',
    label: 'Producteca → Correo Argentino (CA…)',
    tipo: 'PIM — nuevo envío',
    descripcion: 'Despacho por Producteca con tracking Correo Argentino (prefijo CA). Muestra "Correo Argentino" como carrier real.',
    compatibleTemplates: ['pim-nuevo-envio'],
  },
  {
    id: 'pim-nuevo-envio-producteca-oca',
    path: 'examples/pim/shared/nuevo-envio-producteca-oca.json',
    store: 'shared',
    label: 'Producteca → OCA (numérico largo)',
    tipo: 'PIM — nuevo envío',
    descripcion: 'Despacho por Producteca con tracking OCA (número largo >12 dígitos). Muestra "OCA" como carrier real.',
    compatibleTemplates: ['pim-nuevo-envio'],
  },
  {
    id: 'pim-nuevo-envio-producteca-trf',
    path: 'examples/pim/shared/nuevo-envio-producteca-trf.json',
    store: 'shared',
    label: 'Producteca → TRF (numérico corto)',
    tipo: 'PIM — nuevo envío',
    descripcion: 'Despacho por Producteca con tracking TRF (número corto ≤12 dígitos). Muestra "TRF" como carrier real.',
    compatibleTemplates: ['pim-nuevo-envio'],
  },
  {
    id: 'pim-nuevo-envio-producteca-sin-tracking',
    path: 'examples/pim/shared/nuevo-envio-producteca-sin-tracking.json',
    store: 'shared',
    label: 'Producteca — sin tracking aún',
    tipo: 'PIM — nuevo envío',
    descripcion: 'Despacho por Producteca sin número de seguimiento disponible. Muestra el mensaje de espera en lugar del botón.',
    compatibleTemplates: ['pim-nuevo-envio'],
  },
  {
    id: 'pim-nuevo-envio-ocasa',
    path: 'examples/pim/shared/nuevo-envio-ocasa.json',
    store: 'shared',
    label: 'OCASA',
    tipo: 'PIM — nuevo envío',
    descripcion: 'Despacho por OCASA con número de tracking embebido en el link de seguimiento.',
    compatibleTemplates: ['pim-nuevo-envio'],
  },
  {
    id: 'pim-nuevo-envio-propia',
    path: 'examples/pim/shared/nuevo-envio-propia.json',
    store: 'shared',
    label: 'Logística Propia',
    tipo: 'PIM — nuevo envío',
    descripcion: 'Despacho con logística propia. Sin botón de tracking; muestra mensaje de coordinación de entrega.',
    compatibleTemplates: ['pim-nuevo-envio'],
  },
];

const VERSION = {
  number: '1.4.2',
  date: '2026-06-10',
  summary: 'Escenarios completos para nuevo-envio PIM: Andreani, Producteca (4 carriers), OCASA, Propia.',
};

const CHANGELOG = [
  { version: '1.4.0', date: '2026-06-09', summary: 'Inventario PIM, 14 plantillas compartidas en catálogo, renderer PIM mínimo y nuevo-envio v2 con escenario representativo.' },
  { version: '1.3.0', date: '2026-06-08', summary: 'Nueva plantilla orden generada B2B y escenario específico para previsualización.' },
  { version: '0.7.0', date: '2026-06-07', summary: 'Flujo de Correos suma estados por nodo, ficha operativa, acciones para previsualización/creación y soporte de query params en Visualizador.' },
  { version: '0.6.0', date: '2026-06-06', summary: 'Módulo Flujo de Correos con mapa por pestañas para entrega, cambio, devolución y garantía, organizado por plataforma.' },
  { version: '0.5.0', date: '2026-06-06', summary: 'Se priorizan Biblioteca y Visualizador como flujo principal; Simulador queda rotulado como QA interno y se documenta el flujo para crear nuevas plantillas con JSON representativo.' },
  { version: '0.4.0', date: '2026-06-06', summary: 'Datos de ejemplo sanitizados, Handlebars local, escenarios centralizados, simulador coherente en multipaquete y docs de validación/roadmap.' },
  { version: '0.3.0', date: '2026-06-06', summary: 'Simulador de Datos (Módulo 4) con escenarios combinables; fix: normalización de pedidos "desnudos" en el render compartido.' },
  { version: '0.2.0', date: '2026-06-06', summary: 'Visualizador de Plantillas (Módulo 3) con selector de plantilla y escenario, render con Handlebars.' },
  { version: '0.1.0', date: '2026-06-06', summary: 'Estructura inicial y catálogo con pedido-confirmado y pago-aprobado.' },
];
